language: ruby
os: linux
rvm:
- 2.4.1
addons:
  apt:
    update: true
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
before_install:
- nvm install $NODE_VERSION
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NODE_VERSION="8.11.3"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: og9Rjy1DubvM4HjNcF9K5cvhTPTQJhKLHcl7Qj1iN6DVlSGdmamsvkq/3xPbBItm+kNKA8IGbZd83EKohNm6RLqCql5hRrwGQrENRbfp+IqBagCrJYkRg3V6UvLqusKsho/ug9Kqgtl+xYya2TiQFz+Ab71oqHpolPNkWNi8OCoi/odYDK37chwlyJN7bg5nMo2buW1rSBEQOmLGKTRItTbRgVN3XGnDqQv2SppDJgpH4JKrVfSLmbK4BuDWOvqL7Yy90aaguK4a4Cd0O+QaZrv77PXX85/R/CL6h9vLM/0t6pv+v84PrZhvfN9uwFQE3ZqRx4zHZxF95gQnyB/vhYAs7BzPsaCG87nl8S6YVHyNUZI/VsPXZz6VJbr1MNGeZCXvRQLVvwVCXyiCTUKo2OV5wp8CTkQwhlQ5bo20CJnjqcb2QPpKz6Nw/GgZW5Wx592wumxChK/DqxAfGMsWxKPvtGBepIW0dCGURSYj3W8LlCyQFXsz5O8iLlxmUmHPOTiH97kGNgOIcI9Z3BQ9ALlyN/8ioMUV/v0bBMWqYmAfnqHM6UTplyg3ghiM+w8gy+FJQsK6+33MPlSWVu+/hxxnXn/OkP/dRx8F+UOg+QY4wq5FB2dKRQmgpwOSO6RRZIDZU4I5Q4JLs1yG1u3cqGBwz596uF2FBBikDmksWRE=
sudo: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: "./_site"
  committer-from-gh: true
  user: Chen, KunYi(陳坤毅)
  email: kunyi@uwingstech.com
  on:
    branch: master
